// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantsDataAccessLayer.DbContext;

namespace RestaurantsDataAccessLayer.Migrations
{
    [DbContext(typeof(RestaurantsDbContext))]
    [Migration("20191015130145_added location differently")]
    partial class addedlocationdifferently
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestaurantsDomainLayer.Model.Address", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Landmark");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Line2");

                    b.Property<Guid>("RestaurantID");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.HasIndex("RestaurantID")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("RestaurantsDomainLayer.Model.FoodItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cost");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<double>("Rating");

                    b.Property<Guid>("RestaurantId");

                    b.HasKey("ID");

                    b.HasIndex("RestaurantId");

                    b.ToTable("FoodItem");
                });

            modelBuilder.Entity("RestaurantsDomainLayer.Model.Restaurant", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AverageCost");

                    b.Property<int>("DeliveryTime")
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<double>("Rating");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("RestaurantsDomainLayer.Model.Address", b =>
                {
                    b.HasOne("RestaurantsDomainLayer.Model.Restaurant", "Restaurant")
                        .WithOne("Location")
                        .HasForeignKey("RestaurantsDomainLayer.Model.Address", "RestaurantID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RestaurantsDomainLayer.Model.FoodItem", b =>
                {
                    b.HasOne("RestaurantsDomainLayer.Model.Restaurant", "Restaurant")
                        .WithMany("FoodItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
